// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTnM-NUxwddhGA7uN_offVxFuah5F7HE',
    appId: '1:5981672912:web:22acc40ec3706a7c9355d5',
    messagingSenderId: '5981672912',
    projectId: 'optik-okuyucu-app',
    authDomain: 'optik-okuyucu-app.firebaseapp.com',
    storageBucket: 'optik-okuyucu-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC0gUlsX6-MhDf4V7qOmlLOJqlxUmCmyE',
    appId: '1:5981672912:android:e57c9e8d11ce32939355d5',
    messagingSenderId: '5981672912',
    projectId: 'optik-okuyucu-app',
    storageBucket: 'optik-okuyucu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjwrarQa9CEhpf0FjGd3mt6et5USm05TY',
    appId: '1:5981672912:ios:ab1975f71e927a1e9355d5',
    messagingSenderId: '5981672912',
    projectId: 'optik-okuyucu-app',
    storageBucket: 'optik-okuyucu-app.firebasestorage.app',
    iosBundleId: 'com.example.optikOkuyucuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjwrarQa9CEhpf0FjGd3mt6et5USm05TY',
    appId: '1:5981672912:ios:ab1975f71e927a1e9355d5',
    messagingSenderId: '5981672912',
    projectId: 'optik-okuyucu-app',
    storageBucket: 'optik-okuyucu-app.firebasestorage.app',
    iosBundleId: 'com.example.optikOkuyucuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANTnM-NUxwddhGA7uN_offVxFuah5F7HE',
    appId: '1:5981672912:web:8727435c5f4164589355d5',
    messagingSenderId: '5981672912',
    projectId: 'optik-okuyucu-app',
    authDomain: 'optik-okuyucu-app.firebaseapp.com',
    storageBucket: 'optik-okuyucu-app.firebasestorage.app',
  );
}
